name: ❓ Question
description: Ask a question. (For broader discussion, please use Discussions.)
title: "question: <short summary>"
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context / what you've tried
