export type SkillCluster = {
  id: string;
  name: string;
  blurb: string;
  accent: "cyan" | "violet" | "emerald" | "amber";
  skills: { name: string; level?: "core" | "strong" | "familiar" | "exploring" }[];
  relatedProjects?: string[];
};

export const clusters: SkillCluster[] = [
  {
    id: "performance",
    name: "Performance Core",
    blurb: "Low-level engineering for simulation, profiling and runtime optimization.",
    accent: "amber",
    skills: [
      { name: "C++", level: "core" },
      { name: "C", level: "strong" },
      { name: "Profiling", level: "core" },
      { name: "Valgrind", level: "strong" },
      { name: "AddressSanitizer", level: "strong" },
      { name: "GDB", level: "strong" },
      { name: "SystemVerilog", level: "strong" },
      { name: "RTL", level: "strong" },
      { name: "Bash", level: "strong" },
      { name: "Perforce", level: "strong" },
    ],
    relatedProjects: ["xcelium-optimization", "xmai"],
  },
  {
    id: "intelligent",
    name: "Intelligent Systems",
    blurb: "Agentic AI, retrieval, embeddings and computer vision for engineering workflows.",
    accent: "violet",
    skills: [
      { name: "LLMs", level: "core" },
      { name: "RAG", level: "core" },
      { name: "Vector Embeddings", level: "core" },
      { name: "AI Agents", level: "strong" },
      { name: "MCP", level: "strong" },
      { name: "Computer Vision", level: "strong" },
      { name: "OpenCV", level: "strong" },
      { name: "MediaPipe", level: "strong" },
      { name: "NumPy", level: "strong" },
      { name: "Deep Learning", level: "familiar" },
    ],
    relatedProjects: ["xmai", "algolens", "postureiq"],
  },
  {
    id: "backend",
    name: "Distributed Backend",
    blurb: "Service architecture, streaming, identity and storage for scalable systems.",
    accent: "cyan",
    skills: [
      { name: "Java", level: "strong" },
      { name: "Go", level: "strong" },
      { name: "Python", level: "strong" },
      { name: "Node.js", level: "strong" },
      { name: "REST", level: "core" },
      { name: "gRPC", level: "strong" },
      { name: "GraphQL", level: "familiar" },
      { name: "WebSockets", level: "strong" },
      { name: "Micronaut", level: "familiar" },
      { name: "PostgreSQL", level: "strong" },
      { name: "MySQL", level: "strong" },
      { name: "MongoDB", level: "strong" },
      { name: "Redis", level: "strong" },
      { name: "Kafka", level: "familiar" },
    ],
    relatedProjects: ["track-person-app", "smart-brain"],
  },
  {
    id: "product",
    name: "Product Engineering",
    blurb: "Polished, accessible product surfaces with rigorous quality gates.",
    accent: "emerald",
    skills: [
      { name: "React", level: "core" },
      { name: "TypeScript", level: "core" },
      { name: "Redux Toolkit", level: "strong" },
      { name: "RTK Query", level: "strong" },
      { name: "React Native", level: "strong" },
      { name: "Tailwind CSS", level: "core" },
      { name: "Canvas", level: "strong" },
      { name: "Konva", level: "familiar" },
      { name: "Web Workers", level: "strong" },
      { name: "Accessibility", level: "strong" },
      { name: "i18n/RTL", level: "strong" },
      { name: "Playwright", level: "strong" },
      { name: "Storybook", level: "strong" },
    ],
    relatedProjects: ["algolens", "postureiq"],
  },
  {
    id: "infra",
    name: "Infrastructure",
    blurb: "Cloud, containers, observability and developer-experience plumbing.",
    accent: "cyan",
    skills: [
      { name: "AWS", level: "strong" },
      { name: "GCP", level: "strong" },
      { name: "Docker", level: "core" },
      { name: "Kubernetes", level: "strong" },
      { name: "CI/CD", level: "core" },
      { name: "GitHub Actions", level: "strong" },
      { name: "Jenkins", level: "familiar" },
      { name: "Firebase", level: "strong" },
      { name: "Heroku", level: "familiar" },
      { name: "Linux", level: "core" },
      { name: "Git", level: "core" },
      { name: "Sentry", level: "strong" },
      { name: "Web Vitals", level: "strong" },
      { name: "PostHog", level: "familiar" },
    ],
    relatedProjects: ["algolens", "xmai", "track-person-app"],
  },
  {
    id: "reliability-security",
    name: "Reliability & Security",
    blurb: "Identity, hardening, API contracts and production-readiness controls.",
    accent: "amber",
    skills: [
      { name: "OAuth 2.0", level: "strong" },
      { name: "OIDC", level: "strong" },
      { name: "PKCE", level: "strong" },
      { name: "JWT", level: "strong" },
      { name: "CSP", level: "strong" },
      { name: "Rate Limiting", level: "strong" },
      { name: "OpenAPI", level: "strong" },
      { name: "SLOs", level: "familiar" },
      { name: "Secret Management", level: "familiar" },
      { name: "ECDSA", level: "familiar" },
    ],
    relatedProjects: ["algolens", "tezos-premier-league"],
  },
];
