import {
  Activity,
  Bug,
  ShieldAlert,
  Terminal,
  CircuitBoard,
  SquareTerminal,
  GitMerge,
  Brain,
  Search as SearchIcon,
  Network,
  Bot,
  Plug,
  Eye,
  Layers,
  Cable,
  Radio,
  Rocket,
  RefreshCcw,
  Database,
  Smartphone,
  PenTool,
  Shapes,
  Cpu,
  Accessibility as A11yIcon,
  Languages,
  TestTube,
  BookOpen,
  GitBranch,
  Play,
  CloudCog,
  Bell,
  Gauge,
  BarChart3,
  KeyRound,
  IdCard,
  Lock,
  Key,
  Shield,
  Timer,
  FileJson,
  Target,
  Vault,
  Fingerprint,
  Boxes,
  MemoryStick,
  Undo2,
  Binary,
  Users,
  Sparkles,
  ListChecks,
  ClipboardCheck,
  Microscope,
  type LucideIcon,
} from "lucide-react";

// Curated mapping for skills without a brand SVG in TECH_ICONS.
export const SKILL_GLYPHS: Record<string, LucideIcon> = {
  Profiling: Activity,
  "Memory Profiling": MemoryStick,
  Valgrind: Bug,
  AddressSanitizer: ShieldAlert,
  GDB: Terminal,
  "Undo/UDB": Undo2,
  Xcelium: Binary,
  SystemVerilog: CircuitBoard,
  RTL: CircuitBoard,
  Bash: SquareTerminal,
  Perforce: GitMerge,
  LLMs: Brain,
  RAG: SearchIcon,
  "Vector Embeddings": Network,
  "AI Agents": Bot,
  "Multi-Agent Systems": Users,
  "OpenAI Agents SDK": Sparkles,
  MCP: Plug,
  "Structured Outputs": ListChecks,
  "LLM Evaluation": ClipboardCheck,
  "Computer Vision": Eye,
  "Deep Learning": Layers,
  gRPC: Cable,
  WebSockets: Radio,
  Micronaut: Rocket,
  OpenAPI: FileJson,
  "Redux Toolkit": RefreshCcw,
  "RTK Query": Database,
  "React Native": Smartphone,
  Canvas: PenTool,
  Konva: Shapes,
  "Web Workers": Cpu,
  Accessibility: A11yIcon,
  "i18n/RTL": Languages,
  Playwright: TestTube,
  Storybook: BookOpen,
  "CI/CD": GitBranch,
  "GitHub Actions": Play,
  Heroku: CloudCog,
  Sentry: Bell,
  "Web Vitals": Gauge,
  PostHog: BarChart3,
  "OAuth 2.0": KeyRound,
  OIDC: IdCard,
  PKCE: Lock,
  JWT: Key,
  CSP: Shield,
  "Rate Limiting": Timer,
  SLOs: Target,
  "Secret Management": Vault,
  ECDSA: Fingerprint,
  Express: Rocket,
  Terraform: Boxes,
  "VS Code": SquareTerminal,
  Nginx: CloudCog,
  RabbitMQ: Radio,
  Prometheus: Gauge,
  Grafana: BarChart3,
  Jest: TestTube,
  Vitest: TestTube,
  pytest: Microscope,
  Postman: Cable,
  CMake: Boxes,
};

export function SkillFallbackGlyph({ className }: { className?: string }) {
  return <Boxes className={className} />;
}
