"use client";

import {
  Activity,
  Bug,
  ShieldAlert,
  Terminal,
  CircuitBoard,
  SquareTerminal,
  GitMerge,
  Brain,
  Search as SearchIcon,
  Network,
  Bot,
  Plug,
  Eye,
  Layers,
  Cable,
  Radio,
  Rocket,
  RefreshCcw,
  Database,
  Smartphone,
  PenTool,
  Shapes,
  Cpu,
  Accessibility as A11yIcon,
  Languages,
  TestTube,
  BookOpen,
  GitBranch,
  Play,
  CloudCog,
  Bell,
  Gauge,
  BarChart3,
  KeyRound,
  IdCard,
  Lock,
  Key,
  Shield,
  Timer,
  FileJson,
  Target,
  Vault,
  Fingerprint,
  Boxes,
  type LucideIcon,
} from "lucide-react";

// Curated mapping of every skill in the spectrum to a distinguishing glyph.
// Real brand SVGs (TECH_ICONS) take precedence in the consumer — this is the fallback.
export const SKILL_GLYPHS: Record<string, LucideIcon> = {
  Profiling: Activity,
  Valgrind: Bug,
  AddressSanitizer: ShieldAlert,
  GDB: Terminal,
  SystemVerilog: CircuitBoard,
  RTL: CircuitBoard,
  Bash: SquareTerminal,
  Perforce: GitMerge,
  LLMs: Brain,
  RAG: SearchIcon,
  "Vector Embeddings": Network,
  "AI Agents": Bot,
  MCP: Plug,
  "Computer Vision": Eye,
  "Deep Learning": Layers,
  gRPC: Cable,
  WebSockets: Radio,
  Micronaut: Rocket,
  "Redux Toolkit": RefreshCcw,
  "RTK Query": Database,
  "React Native": Smartphone,
  Canvas: PenTool,
  Konva: Shapes,
  "Web Workers": Cpu,
  Accessibility: A11yIcon,
  "i18n/RTL": Languages,
  Playwright: TestTube,
  Storybook: BookOpen,
  "CI/CD": GitBranch,
  "GitHub Actions": Play,
  Heroku: CloudCog,
  Sentry: Bell,
  "Web Vitals": Gauge,
  PostHog: BarChart3,
  "OAuth 2.0": KeyRound,
  OIDC: IdCard,
  PKCE: Lock,
  JWT: Key,
  CSP: Shield,
  "Rate Limiting": Timer,
  OpenAPI: FileJson,
  SLOs: Target,
  "Secret Management": Vault,
  ECDSA: Fingerprint,
};

// Fallback when nothing is mapped — a deterministic accent box (avoids initials).
export function SkillFallbackGlyph({ className }: { className?: string }) {
  const C = Boxes;
  return <C className={className} />;
}
